server:
  port: 8080

---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: roommanagement
          uri: localhost:8083
          predicates:
            - Path=/roommanagements/**
        - id: reservationmanagement
          uri: localhost:8081
          predicates:
            - Path=/reservationmanagements/**
        - id: paymentmanagement
          uri: localhost:8082
          predicates:
            - Path=/paymentmanagements/**

---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: roommanagement
          uri: roommanagement:8080
          predicates:
            - Path=/roommanagements/**
        - id: reservationmanagement
          uri: reservationmanagement:8080
          predicates:
            - Path=/reservationmanagements/**
        - id: paymentmanagement
          uri: paymentmanagement:8080
          predicates:
            - Path=/paymentmanagements/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
server:
  port: 8080