spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservationManagement
          uri: http://localhost:8081
          predicates:
            - Path=/reservationManagements/**
        - id: payments
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**
        - id: roommanagement
          uri: http://localhost:8083
          predicates:
            - Path=/roomManagements/**
        - id: roominfo
          uri: http://localhost:8084
          predicates:
            - Path=/roomInfoes/**
        - id: couponManagement
          uri: http://localhost:8085
          predicates:
            - Path=/coupons/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservationmanagement
          uri: http://reservationmanagement:8080
          predicates:
            - Path=/reservationmanagements/**
        - id: payments
          uri: http://payments:8080
          predicates:
            - Path=/payments/**
        - id: roommanagement
          uri: http://roommanagement:8080
          predicates:
            - Path=/roommanagements/**
        - id: roominfo
          uri: http://roominfo:8080
          predicates:
            - Path=/roominfoes/**
        - id: couponmanagement
          uri: http://couponmanagement:8080
          predicates:
            - Path=/coupons/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
